### ISSUE TITLE
Add pip install support to scikit-beam

### ISSUE THREAD

**Issue by ronpandolfi** [lightsources/project-management#35]

**Comment by dylanmcreynolds** [comment]
Work is complete, Ron tested.

**Comment by ronpandolfi** [comment]
The correlation modules need `scikit-image` added to requirements
https://github.com/scikit-beam/scikit-beam/issues/556

**Comment by dylanmcreynolds** [comment]
This isn't assigned to anyone. Who is working on it?

**Comment by mrakitin** [comment]
I was working on that, but without an assignment. Let me fix https://github.com/scikit-beam/scikit-beam/pull/554 and then I'll take care of the missing dep (https://github.com/scikit-beam/scikit-beam/issues/556).

**Comment by dylanmcreynolds** [comment]
@mrakitin This issue is closed, yes?

**Comment by mrakitin** [comment]
I will be ready to answer by our Friday call. I need to re-check.

**Comment by mrakitin** [comment]
Actually, I think it won't be entirely possible to build the package since it has a dependency of xraylib, which is not on PyPI, so it makes a little sense as xraylib is going to be installed from conda anyway, and we have a reliable package for scikit-beam for all 3 platforms there already (https://github.com/nsls-ii-forge/scikit-beam-feedstock). I think this issue can be closed as "won't implement". Please reopen if you think it's still needed.
